name: Backend CI

on:
  push:
    paths:
      - 'CarDexBackend/**'
  pull_request:
    paths:
      - 'CarDexBackend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore CarDexBackend.sln

      - name: Build solution
        run: dotnet build CarDexBackend.sln --no-restore --configuration Debug

      - name: Run tests with coverage
        run: |
          dotnet test CarDexBackend.sln \
            --no-build \
            --configuration Debug \
            --collect:"XPlat Code Coverage" \
            --results-directory TestResults \
            /p:CoverletOutputFormat=cobertura

      - name: Generate HTML coverage report
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator \
            -reports:TestResults/**/coverage.cobertura.xml \
            -targetdir:CoverageReport \
            -reporttypes:Html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: CoverageReport

